matrix:
  include:
  - language: node_js
    os: linux
    dist: xenial
    node_js:
    - 10
    cache: yarn
    addons:
      apt:
        sources:
          - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
            key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
        packages:
          - yarn
    before_install:
    - wget https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz
    - tar -xzvf protobuf-cpp-3.6.1.tar.gz
    - pushd protobuf-3.6.1
    - ./configure --disable-shared && make && sudo make install
    - popd
    script:
    - pushd rsocket-rpc-js
    - yarn install && yarn protoc && yarn test
    - popd
    - pushd rsocket-rpc-protobuf
    - yarn install && yarn prebuild
    - popd
  - language: node_js
    os: osx
    osx_image: xcode10.1
    node_js:
    - 10
    cache: yarn
    addons:
      apt:
        sources:
          - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
            key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
        packages:
          - yarn
    before_install:
    - curl -O -L https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz
    - tar -xzf protobuf-cpp-3.6.1.tar.gz
    - pushd protobuf-3.6.1
    - ./autogen.sh
    - ./configure --disable-shared && make && sudo make install
    - popd
    script:
    - pushd rsocket-rpc-protobuf
    - yarn install && yarn prebuild
    - popd
  - language: node_js
    os: windows
    node_js:
    - 10
    cache: yarn
    addons:
      apt:
        sources:
          - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
            key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
        packages:
          - yarn
    before_install:
    - wget https://github.com/google/protobuf/releases/download/v3.6.1/protobuf-cpp-3.6.1.tar.gz
    - tar -xzf protobuf-cpp-3.6.1.tar.gz
    - pushd protobuf-3.6.1/cmake
    - mkdir build && cd build
    - cmake -DCMAKE_CXX_FLAGS="-std=c++11 -EHsc" -Dprotobuf_BUILD_TESTS=OFF ..
    - cmake --build . --config Release --target install
    - popd
    script:
    - pushd rsocket-rpc-protobuf
    - npm config set cmake_Protobuf_LIBRARIES="C:/Program Files (x86)/protobuf/lib/"
    - npm config set cmake_Protobuf_INCLUDE_DIR="C:/Program Files (x86)/protobuf/include/"
    - npm config set cmake_Protobuf_LIBRARY="C:/Program Files (x86)/protobuf/lib/libprotobuf.lib"
    - npm config set cmake_Protobuf_PROTOC_LIBRARY="C:/Program Files (x86)/protobuf/lib/libprotoc.lib"
    - yarn install && yarn prebuild
    - popd