sudo: required
matrix:
  include:
  - os: linux
    jdk: oraclejdk8
    language: generic
    before_install:
    - wget https://github.com/google/protobuf/releases/download/v3.6.0/protobuf-cpp-3.6.0.tar.gz
    - tar -xzvf protobuf-cpp-3.6.0.tar.gz
    - pushd protobuf-3.6.0 && ./configure --disable-shared && make && sudo make install
      && popd
    script: rsocket-rpc-java/buildtravis.sh
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
notifications:
  email: false
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2"
env:
  global:
  - secure: jjD+NoVaXEd1qKSG1hUae5HNDqU2y63NuOeKqdm3WlDlbfVo895PMHI3SSGW8iyDVLy9wl8Qx4DHKlW0gYpJB347oc8nNFnd4TEIMZNkCwVSpmYvOXYctSk/ZmJtKNGhejOoRA7RGXRSyYCmXJWxD/qjXKCfvHWhHNF/ELEo/HyaKyreg50XOxYK41czibUdrZAGtfmx31hyi4dYANYZKO+X16fY7aSQOlwdmRlHadPaMItpMDeuV92KDyJlBGB2DYTflPXkvFhNuECAlq/K19H0I79RkPaQETZI9gA4eWem0+gMnAsf2AE2n5EPIte//FLDFt9RvTi+vbcNlPvDQWAGIXwkXpl57tsMRFjKTpGbJT/jTZ6mfKmpVbqb7mjuMNWfXHyG63D34+RMHDWFaIL9mb2Dtv+mdMKKGRNetPhKGiOVM9vsChn4v7R1pFx/9SiZ2cVLnF2YJz+9chL1u1dr502qfVzevluQc24dbAwpAiQiSiRzeLxmW4X+49V7bXTQo4fu8VlclKpOcRGJHvl55hV1VlSeFUys1jd//LXtQoyJ0G5kBpWVkSUpIrOQ8vD+6a63jnCY5ZWHNAQqTCQf6BwTel/ALbnh2VwRUT2IdqOdNV6TGhJzHWpODD3UQakeDQkyUvN+zc0PevDxAxBn82j5qXAdUHY8GtZ2Mno=
  - secure: Lxma+syNjxh2jRXxLOYaXnSOobe/UHwj2/H3ddZjrw4BI3Erm/GHkGtxOBdQCsN9fG6rqJLEzoowSmGcwu+YCualkOs0QRtddKrmrPeaw7gbE+EilamXPR9Vl98QsBajZhdLvff698CAYIB9IiKREMY3EPvUPQiMCLCcNJveqPhFdcYa1VrTyoSuIqhIrNEW/wqbHBsw6V+GCxl72E3I3MYxq45qW7ZrGU8nPDncHIVImAqaSzH0lazMeTtMtFFave3MhYGEJngINdykKtdbMG8fhH4vKqE6vDKq2Wxd/HgRPPTqYae/TeGOTEMs/1cbbyp4aB8H9j4mLGSyvxKBOTzP/hLL9B4/Bn3s5vdq9yFoGo0sv0YdAhfhfbHI3JPIBvMDovLe970ruq6h4KqP5uxeJHErrVkk9sxzBiXw0+9uVY56oJMDZPrQlPn0xX/ViMo18Ww7CzmaVPWTF1yEDJVEFmtHmWx0Bh7KyD33jyBDP5dZWbRA0Tx97YT7v0Ah6bG8PzxLgkws9Q/k6lr5tFyZFKStEgg2NYDe0OOwZBnC3mLlzRVBPmBfFupzXpnq6ya4V4+utCMabeh8CERtA7Re8IL7iHMX5D2wc2H/PjdFqU4Yy5GrbSCls9fmoP2eWuQ2wsTBYfy+eb7lkBh5YxY7F/XtwnG7ugRW0smbfxU=
